var_out =[]
olvar = "MVNOKHSCGEdxPSsYcEnvWCXFFkwZAuadcTpiBfSyYkkGbWfFrcEJuUjdgXrtsFZWI{GbNDdwPvxduXnlvZCcbyrqbSmHlTTbxnkPLxenfFUXz0aIUAjmftxRQuvZPFTQwIMbENWOgghuZYSxFDfcRrzkkyovMixzHExpkAdpgab_QZFPMzPRzDhBuKqXpTZupmwmjxZJtcXCfliXycQgFOoQHjMzwmnAGklXTQpQpOorCzvNwQnWwudJphS4bItwqxRPjgQmZsXoJoDudmCRCfKAOdgfuWBRuGSJRzfnkckktbOFbPFUhsfOLvVCgtSSNRRqbvCvnSUrRpwDEEtTLHz_xVxSVTgxjIjjKJLQhicECzavIgLoHCExourDPLlrLfrmGdabjoiTk5WQqSyjSMjmENKJHaQZqxLanSZWoSFMxEMrICRZbkiKytvxjAITBiGnAIaND3BOtHajsFZjduZsPlnrpKSmqohKEOvevpvpvdIcILLlDJYjggTsZTHrkJCDRCH3UfuqqeVsuAEhNAXbQLVPcMAcFUjtfqoGJwdyAcZQkdZijGGgUTXNwEVAMNsGzUQGsFp_XMjbRVHjSEwfKOOHFtyKmMfViPQewMKslgYvwJPdgiNulOCktVMnlNwxPVsiVlAhkowQydgpTBAuDXlViySfeBUJfaxxbyfVYgGrlXUOOuNOGsRaBgYzbnvMcayZeZjbLWvTViXoZrHGsmLcCrmlINHZrwelNuPmGzmAwiQwnLEYpHhAFTYzzkiIXIDndIBYfrXgmOoeqxiKkEEgHoBbusXyfpqMmMKCi1oFPEucltKZhIYrfuKZceluARvKJTIxVEBoesheEZYyQbvfMJJixcJnKwtZKRkvhxzAJSKEloqFhRdpNkoJwmiavvKeOeMZaSOGwaMRUrXJrDcaQgdvsHdVxMpfVScGVGzdeFWzmjQVmSAKkaRRbLPEdwqsQvIRUJHzQgDMCbRIwVy3PoykpmBqWBvhJFhBaQDEYyuPTrvHauBIRFrcmgUYoMqQeHNALvxvqmyVgeLJbTgKMIRXUScsmrOOZPFQNSoEYpNyPYiHEswba_FyxbkKYfOGKlFDrkUyVzdiJhDJxMlRGmjibXqfuQAKvpSxsOVWYCOlVvUDGrmfnoduZMNQpRXrDuOOhypyLByvbNhjpoeoTlcLGkWnLiHynGeTMBTOoByWxrVYSsyuDgiKEJaiXpbYBQQVMakQbPYHpDyMUSfkVazOCnQscwBmJrQsFEPRAiMVmvajTKoKBtDlIfiTTQtFpjM0fKqyBUWClujBJNALFVuJbMzzySuYRJvDgrHXwpKiWbHXyhEqISQnwgKlgawyJFiXThPGWekSqBXorobZzYsZWnEFoiKOJdgAVwLXhHGsFHrwHGsvwkGBSKkQeIIHGotplpPkQAoZYiWSsnaLJTOIewEnUruvefOBnbkYEFezZwygQPZXUoLvVFROJGKeqiGLZiqstmNMeqTkIpuFKBrhYIbil3ydhXrNDxZDbZtYChztminNhOQFnICFxztCbPzVGhAmVMJsYpdXcqiAsZcbJnFJDUpVqNfHPKNRSUunsdEZoPFrYcszIbAasDScymVHSjkreAzrXlW3IuybisfprRSAvDfDeGAxYSOWPvaEPNrbCeVoBevjVogQMYQLZJEupawsAyKpzdZnGGrwAknSRNqaRzywRJJqklJFezOqCnjdGpKtOhHOICVygxJtNzhFIKAOLspqFxY2flsokUCqLLiQDMhNpewoBLgtRqIFWxrMHkklPxLVZEOhpGlrmYJPuzeDKShwxJKayUsIpfXhBpxKfXGmbgrEATDUrKtWhilqpfHDNcDBsbKfQPTXdfOrTSYYrSbAkXFSaxy1efmFliKxWBcyXtDeYLPMnXkVrhFqzKZtHaalgatnMDUTJfOfzWZCbKbtyLGgufkZnQGUhPxAvhxTKmbPPtqIXmQEfhpllZgUpPgWwrNjyzgedxXPKojHgzsLlARMeTcoSUflyqVlI?CVNCPUvSGIzOgleSZWIyohSCTWBGtbrUgBTUixRZtBfMdoZijiZmAMbHjUrusvdzTMXJkBzoJNbvNyRcFVlBqTznkVJttKwXmwlflYRmSyYmidTWdUgIOgxWzDtOdExLyJtYSmyEmlq}dVMQJDHabZZIjljeXatWLQJsyDAonpUGXkHfiGDOwCqQwgZTUjBjCASSdSzneMrSRdSnvDAqXLpfVWEUxXLgsUjSctcPOsItMvYPytLyeYvAjazrSSXAjMFWHsaxKhTcPNwoNcQZeazIRmScicDvRoTSMOCNaBeLGVHirQPuxAFrKPXcJNruJhaEyqwyaunHBzRhhGHnxjsQswFeCOqWtEHnekqEGvSwLBfvyFZQFhWAarkeXHoDNAUlHBgOCaSBKjMusnKqIpMAqnmdqsoDCjFtBsWHICFJVabOYvBapAZ"

for num in range(1, 150):

	if num > 1:
		for i in range(2, num):
			if (num % i) == 0:
				break
		else:
			#print(num)
			for j in range(0,num+1):
				if(j==0):
					var_out.append(olvar[j])
				elif j==num:
					olvar = olvar[num+1 : : ]

for i in var_out:
	print(i,end='')